### ISSUE TITLE
Component: X 

### ISSUE THREAD

**Issue by rtmill** [rtmill/OncologyWG#1]
# Problem Space

Text here

# Proposed Solutions

Text/links here

## Tasks
- [ ] Open up for group discussion
- [ ] Finalize decisions/requirements
- [ ] Identify outstanding work; Create issues
- [ ] Complete outstanding work: (X)
- [ ] Submit vocabulary modifications: (X)
- [ ] Document : (X)
- [ ] Designate as 'ready for use': (X)
